"""v7: pessoa x empresa x vínculo, contas de sistema, cobrança com split por NF-e,
segurança (limites, aparelhos, desafios, contestação) e produtos PJ.

ATENÇÃO -- migração DESTRUTIVA: apaga as tabelas da v6 e cria o schema v7 do
zero. A v6 misturava pessoa e empresa na mesma linha e usava uma conta "Governo"
com três papéis; não há conversão automática segura desses dados. Até aqui só
existiam bancos de desenvolvimento/teste. Se algum ambiente tiver dados que
importam, exporte antes de rodar `alembic upgrade head`.

Revision ID: c7a1e0f2b3d4
Revises: b2c7f1a9d3e4
Create Date: 2026-10-06 21:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "c7a1e0f2b3d4"
down_revision: Union[str, Sequence[str], None] = "b2c7f1a9d3e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tabelas da v6, em ordem segura para DROP (dependentes primeiro).
_TABELAS_V6 = [
    "split_liquidacoes", "historico_saldo", "cartoes", "refresh_tokens", "sessoes_mfa",
    "transacoes", "carteiras", "usuarios", "split_regras", "logs_auditoria",
]
_ENUMS_V6 = ["tipo_pessoa", "papel_usuario", "auth_metodo"]


def upgrade() -> None:
    for t in _TABELAS_V6:
        op.execute(f"DROP TABLE IF EXISTS {t}")
    if op.get_bind().dialect.name == "postgresql":
        for e in _ENUMS_V6:
            op.execute(f"DROP TYPE IF EXISTS {e}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=180), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=180), nullable=True),
    sa.Column('porte', sa.String(length=10), nullable=False),
    sa.Column('regime_apuracao', sa.Enum('REGULAR', 'SIMPLES', 'MEI', name='regime_apuracao'), nullable=False),
    sa.Column('cnae', sa.String(length=10), nullable=True),
    sa.Column('situacao_cadastral', sa.String(length=30), nullable=True),
    sa.Column('verificada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verificada_por', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ator', sa.String(length=80), nullable=False),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detalhe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repasses_tributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cbs_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ibs_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('corte', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('USUARIO', 'ADMIN', name='papel_usuario'), nullable=False),
    sa.Column('embedding_facial_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('carteiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titular_tipo', sa.Enum('PF', 'PJ', 'SISTEMA', name='tipo_pessoa'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('sistema', sa.String(length=20), nullable=True),
    sa.Column('agencia', sa.String(length=4), nullable=False),
    sa.Column('numero', sa.String(length=12), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_bloqueado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sistema')
    )
    with op.batch_alter_table('carteiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carteiras_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carteiras_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_carteiras_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('creditos_tributarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tributo', sa.String(length=4), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('consultado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creditos_tributarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creditos_tributarios_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('desafios_biometria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publico_id', sa.String(length=40), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('desafios_biometria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_desafios_biometria_publico_id'), ['publico_id'], unique=True)

    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('confiavel', sa.Boolean(), nullable=False),
    sa.Column('confiavel_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'id_hash', name='uq_dispositivo_usuario')
    )
    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispositivos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('operacoes_pendentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('decidido_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['decidido_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operacoes_pendentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operacoes_pendentes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('substituido_por', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('sessoes_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=180), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detalhe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes_mfa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_mfa_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_mfa_referencia'), ['referencia'], unique=False)
        batch_op.create_index('ix_sessoes_tipo_criado', ['tipo', 'criado_em'], unique=False)

    op.create_table('vinculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'APROVADOR', 'OPERADOR', 'CONSULTA', name='papel_vinculo'), nullable=False),
    sa.Column('alcada', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'empresa_id', name='uq_vinculo_usuario_empresa')
    )
    with op.batch_alter_table('vinculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vinculos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vinculos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('segredo', sa.String(length=80), nullable=False),
    sa.Column('eventos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('autorizacoes_recorrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recebedor_carteira_id', sa.Integer(), nullable=False),
    sa.Column('pagador_carteira_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=140), nullable=False),
    sa.Column('valor_maximo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('periodicidade', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('aceita_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pagador_carteira_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['recebedor_carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autorizacoes_recorrentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autorizacoes_recorrentes_pagador_carteira_id'), ['pagador_carteira_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autorizacoes_recorrentes_recebedor_carteira_id'), ['recebedor_carteira_id'], unique=False)

    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(length=60), nullable=False),
    sa.Column('numero_masc', sa.String(length=32), nullable=False),
    sa.Column('bandeira', sa.String(length=20), nullable=False),
    sa.Column('validade', sa.String(length=5), nullable=False),
    sa.Column('virtual', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('compras_online', sa.Boolean(), nullable=False),
    sa.Column('compras_internacionais', sa.Boolean(), nullable=False),
    sa.Column('limite', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cartoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cartoes_carteira_id'), ['carteira_id'], unique=False)

    op.create_table('chaves_pix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'valor', name='uq_chave_tipo_valor')
    )
    with op.batch_alter_table('chaves_pix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chaves_pix_carteira_id'), ['carteira_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chaves_pix_valor'), ['valor'], unique=False)

    op.create_table('limites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('por_transacao', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('diurno', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('noturno', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pendente_por_transacao', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pendente_diurno', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pendente_noturno', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pendente_vigente_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carteira_id')
    )
    op.create_table('rendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('saldo_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa_diaria', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carteira_id', 'data', name='uq_rendimento_carteira_dia')
    )
    with op.batch_alter_table('rendimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rendimentos_carteira_id'), ['carteira_id'], unique=False)

    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_carteira_id', sa.Integer(), nullable=False),
    sa.Column('destino_carteira_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cbs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ibs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('liquido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo_destino', sa.Enum('PF', 'PJ', 'SISTEMA', name='tipo_pessoa'), nullable=False),
    sa.Column('aplicou_split', sa.Boolean(), nullable=False),
    sa.Column('auth_metodo', sa.Enum('SENHA', 'SELFIE', 'APROVACAO', 'AUTOMATICO', 'SISTEMA', name='auth_metodo'), nullable=False),
    sa.Column('status', sa.Enum('CONCLUIDA', 'RETIDA', 'DEVOLVIDA', 'DEVOLVIDA_PARCIAL', name='status_transacao'), nullable=False),
    sa.Column('bloqueio_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autor_usuario_id', sa.Integer(), nullable=True),
    sa.Column('dispositivo_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=140), nullable=True),
    sa.Column('verificacao_facial', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('transacao_original_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['autor_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['destino_carteira_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.ForeignKeyConstraint(['origem_carteira_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['transacao_original_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacoes_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacoes_destino_carteira_id'), ['destino_carteira_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacoes_origem_carteira_id'), ['origem_carteira_id'], unique=False)

    op.create_table('webhook_entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('ultima_resposta', sa.String(length=300), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_entregas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_entregas_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('cobrancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(length=35), nullable=False),
    sa.Column('recebedor_carteira_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=140), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('pagador_documento', sa.String(length=14), nullable=True),
    sa.Column('nfe_chave', sa.String(length=44), nullable=True),
    sa.Column('cbs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ibs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('linha_digitavel', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('grupo_parcelamento', sa.String(length=35), nullable=True),
    sa.Column('parcela_numero', sa.Integer(), nullable=False),
    sa.Column('parcelas_total', sa.Integer(), nullable=False),
    sa.Column('autorizacao_id', sa.Integer(), nullable=True),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('paga_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['autorizacao_id'], ['autorizacoes_recorrentes.id'], ),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['recebedor_carteira_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cobrancas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobrancas_grupo_parcelamento'), ['grupo_parcelamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobrancas_nfe_chave'), ['nfe_chave'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobrancas_recebedor_carteira_id'), ['recebedor_carteira_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobrancas_txid'), ['txid'], unique=True)

    op.create_table('contestacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('aberta_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=280), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('valor_devolvido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('decidida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aberta_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transacao_id')
    )
    op.create_table('historico_saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_novo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bloqueado_anterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bloqueado_novo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=40), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_saldo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_saldo_carteira_id'), ['carteira_id'], unique=False)

    op.create_table('split_liquidacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('natureza', sa.String(length=20), nullable=False),
    sa.Column('carteira_destino_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('repasse_id', sa.Integer(), nullable=True),
    sa.Column('estornada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_destino_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['repasse_id'], ['repasses_tributo.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('split_liquidacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_split_liquidacoes_repasse_id'), ['repasse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_split_liquidacoes_transacao_id'), ['transacao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("A v7 não volta para a v6 (mudança de modelo de dados). Restaure um backup.")
