"""schema inicial payflow v6

Revision ID: d5de030077b2
Revises: 
Create Date: 2026-10-05 19:23:19.638081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5de030077b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ator', sa.String(length=80), nullable=False),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detalhe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_regras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vigencia', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('aliquota_cbs', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('aliquota_ibs', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vigencia')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('PF', 'PJ', 'GOV', name='tipo_pessoa'), nullable=False),
    sa.Column('documento', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('USUARIO', 'ADMIN', name='papel_usuario'), nullable=False),
    sa.Column('embedding_facial_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('carteiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=64), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carteiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carteiras_chave'), ['chave'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('substituido_por', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('sessoes_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=180), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detalhe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes_mfa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_mfa_referencia'), ['referencia'], unique=False)
        batch_op.create_index('ix_sessoes_tipo_criado', ['tipo', 'criado_em'], unique=False)

    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_carteira_id', sa.Integer(), nullable=False),
    sa.Column('destino_carteira_id', sa.Integer(), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cbs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ibs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('liquido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo_destino', sa.Enum('PF', 'PJ', 'GOV', name='tipo_pessoa'), nullable=False),
    sa.Column('aplicou_split', sa.Boolean(), nullable=False),
    sa.Column('auth_metodo', sa.Enum('SENHA', 'SELFIE', name='auth_metodo'), nullable=False),
    sa.Column('verificacao_facial', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destino_carteira_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['origem_carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('historico_saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_novo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=40), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_saldo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_saldo_carteira_id'), ['carteira_id'], unique=False)

    op.create_table('split_liquidacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('natureza', sa.String(length=20), nullable=False),
    sa.Column('carteira_destino_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_destino_id'], ['carteiras.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('split_liquidacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_split_liquidacoes_transacao_id'), ['transacao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_liquidacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_split_liquidacoes_transacao_id'))

    op.drop_table('split_liquidacoes')
    with op.batch_alter_table('historico_saldo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_saldo_carteira_id'))

    op.drop_table('historico_saldo')
    op.drop_table('transacoes')
    with op.batch_alter_table('sessoes_mfa', schema=None) as batch_op:
        batch_op.drop_index('ix_sessoes_tipo_criado')
        batch_op.drop_index(batch_op.f('ix_sessoes_mfa_referencia'))

    op.drop_table('sessoes_mfa')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('carteiras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carteiras_chave'))

    op.drop_table('carteiras')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('split_regras')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
