"""beneficios pf: loja, viagens, pontos e setor

Revision ID: e4f5a6b7c8d9
Revises: c7a1e0f2b3d4
Create Date: 2026-10-06 21:14:03.600626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f5a6b7c8d9'
down_revision: Union[str, Sequence[str], None] = 'c7a1e0f2b3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=280), nullable=False),
    sa.Column('preco', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('lojista_carteira_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lojista_carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=3), nullable=False),
    sa.Column('origem_cidade', sa.String(length=60), nullable=False),
    sa.Column('destino', sa.String(length=3), nullable=False),
    sa.Column('destino_cidade', sa.String(length=60), nullable=False),
    sa.Column('companhia', sa.String(length=40), nullable=False),
    sa.Column('saida', sa.String(length=5), nullable=False),
    sa.Column('chegada', sa.String(length=5), nullable=False),
    sa.Column('duracao', sa.String(length=10), nullable=False),
    sa.Column('direto', sa.Boolean(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('milhas', sa.Integer(), nullable=False),
    sa.Column('parceiro_carteira_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parceiro_carteira_id'], ['carteiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos_movimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=140), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pontos_movimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pontos_movimentos_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor', sa.String(length=80), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('pontos')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('setor')

    with op.batch_alter_table('pontos_movimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pontos_movimentos_usuario_id'))

    op.drop_table('pontos_movimentos')
    op.drop_table('voos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
