/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AppAjudaRouteImport } from './routes/_app.ajuda'
import { Route as AppAuditoriaRouteImport } from './routes/_app.auditoria'
import { Route as AppCartoesRouteImport } from './routes/_app.cartoes'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppContasRouteImport } from './routes/_app.contas'
import { Route as AppConvitesRouteImport } from './routes/_app.convites'
import { Route as AppDepositarRouteImport } from './routes/_app.depositar'
import { Route as AppEquipeRouteImport } from './routes/_app.equipe'
import { Route as AppExtratoRouteImport } from './routes/_app.extrato'
import { Route as AppFolhaRouteImport } from './routes/_app.folha'
import { Route as AppInicioRouteImport } from './routes/_app.inicio'
import { Route as AppNotificacoesRouteImport } from './routes/_app.notificacoes'
import { Route as AppPendentesRouteImport } from './routes/_app.pendentes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPixRouteImport } from './routes/_app.pix'
import { Route as AppSegurancaRouteImport } from './routes/_app.seguranca'
import { Route as AppSplitRouteImport } from './routes/_app.split'
import { Route as AppTransferirRouteImport } from './routes/_app.transferir'
import { Route as AppComprovanteIdRouteImport } from './routes/_app.comprovante.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAjudaRoute = AppAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesRoute = AppCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppConvitesRoute = AppConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositarRoute = AppDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppFolhaRoute = AppFolhaRouteImport.update({
  id: '/folha',
  path: '/folha',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPendentesRoute = AppPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPixRoute = AppPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => AppRoute,
} as any)
const AppSegurancaRoute = AppSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AppRoute,
} as any)
const AppSplitRoute = AppSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferirRoute = AppTransferirRouteImport.update({
  id: '/transferir',
  path: '/transferir',
  getParentRoute: () => AppRoute,
} as any)
const AppComprovanteIdRoute = AppComprovanteIdRouteImport.update({
  id: '/comprovante/$id',
  path: '/comprovante/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/ajuda': typeof AppAjudaRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/cartoes': typeof AppCartoesRoute
  '/config': typeof AppConfigRoute
  '/contas': typeof AppContasRoute
  '/convites': typeof AppConvitesRoute
  '/depositar': typeof AppDepositarRoute
  '/equipe': typeof AppEquipeRoute
  '/extrato': typeof AppExtratoRoute
  '/folha': typeof AppFolhaRoute
  '/inicio': typeof AppInicioRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/pendentes': typeof AppPendentesRoute
  '/perfil': typeof AppPerfilRoute
  '/pix': typeof AppPixRoute
  '/seguranca': typeof AppSegurancaRoute
  '/split': typeof AppSplitRoute
  '/transferir': typeof AppTransferirRoute
  '/comprovante/$id': typeof AppComprovanteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/ajuda': typeof AppAjudaRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/cartoes': typeof AppCartoesRoute
  '/config': typeof AppConfigRoute
  '/contas': typeof AppContasRoute
  '/convites': typeof AppConvitesRoute
  '/depositar': typeof AppDepositarRoute
  '/equipe': typeof AppEquipeRoute
  '/extrato': typeof AppExtratoRoute
  '/folha': typeof AppFolhaRoute
  '/inicio': typeof AppInicioRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/pendentes': typeof AppPendentesRoute
  '/perfil': typeof AppPerfilRoute
  '/pix': typeof AppPixRoute
  '/seguranca': typeof AppSegurancaRoute
  '/split': typeof AppSplitRoute
  '/transferir': typeof AppTransferirRoute
  '/comprovante/$id': typeof AppComprovanteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/bem-vindo': typeof BemVindoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_app/ajuda': typeof AppAjudaRoute
  '/_app/auditoria': typeof AppAuditoriaRoute
  '/_app/cartoes': typeof AppCartoesRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/contas': typeof AppContasRoute
  '/_app/convites': typeof AppConvitesRoute
  '/_app/depositar': typeof AppDepositarRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/extrato': typeof AppExtratoRoute
  '/_app/folha': typeof AppFolhaRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/pendentes': typeof AppPendentesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pix': typeof AppPixRoute
  '/_app/seguranca': typeof AppSegurancaRoute
  '/_app/split': typeof AppSplitRoute
  '/_app/transferir': typeof AppTransferirRoute
  '/_app/comprovante/$id': typeof AppComprovanteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bem-vindo'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/ajuda'
    | '/auditoria'
    | '/cartoes'
    | '/config'
    | '/contas'
    | '/convites'
    | '/depositar'
    | '/equipe'
    | '/extrato'
    | '/folha'
    | '/inicio'
    | '/notificacoes'
    | '/pendentes'
    | '/perfil'
    | '/pix'
    | '/seguranca'
    | '/split'
    | '/transferir'
    | '/comprovante/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bem-vindo'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/ajuda'
    | '/auditoria'
    | '/cartoes'
    | '/config'
    | '/contas'
    | '/convites'
    | '/depositar'
    | '/equipe'
    | '/extrato'
    | '/folha'
    | '/inicio'
    | '/notificacoes'
    | '/pendentes'
    | '/perfil'
    | '/pix'
    | '/seguranca'
    | '/split'
    | '/transferir'
    | '/comprovante/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/bem-vindo'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/_app/ajuda'
    | '/_app/auditoria'
    | '/_app/cartoes'
    | '/_app/config'
    | '/_app/contas'
    | '/_app/convites'
    | '/_app/depositar'
    | '/_app/equipe'
    | '/_app/extrato'
    | '/_app/folha'
    | '/_app/inicio'
    | '/_app/notificacoes'
    | '/_app/pendentes'
    | '/_app/perfil'
    | '/_app/pix'
    | '/_app/seguranca'
    | '/_app/split'
    | '/_app/transferir'
    | '/_app/comprovante/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BemVindoRoute: typeof BemVindoRoute
  CriarContaRoute: typeof CriarContaRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ajuda': {
      id: '/_app/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AppAjudaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria': {
      id: '/_app/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes': {
      id: '/_app/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AppCartoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas': {
      id: '/_app/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/convites': {
      id: '/_app/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof AppConvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depositar': {
      id: '/_app/depositar'
      path: '/depositar'
      fullPath: '/depositar'
      preLoaderRoute: typeof AppDepositarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extrato': {
      id: '/_app/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/folha': {
      id: '/_app/folha'
      path: '/folha'
      fullPath: '/folha'
      preLoaderRoute: typeof AppFolhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pendentes': {
      id: '/_app/pendentes'
      path: '/pendentes'
      fullPath: '/pendentes'
      preLoaderRoute: typeof AppPendentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pix': {
      id: '/_app/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof AppPixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguranca': {
      id: '/_app/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AppSegurancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/split': {
      id: '/_app/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof AppSplitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transferir': {
      id: '/_app/transferir'
      path: '/transferir'
      fullPath: '/transferir'
      preLoaderRoute: typeof AppTransferirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comprovante/$id': {
      id: '/_app/comprovante/$id'
      path: '/comprovante/$id'
      fullPath: '/comprovante/$id'
      preLoaderRoute: typeof AppComprovanteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAjudaRoute: typeof AppAjudaRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCartoesRoute: typeof AppCartoesRoute
  AppConfigRoute: typeof AppConfigRoute
  AppContasRoute: typeof AppContasRoute
  AppConvitesRoute: typeof AppConvitesRoute
  AppDepositarRoute: typeof AppDepositarRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppExtratoRoute: typeof AppExtratoRoute
  AppFolhaRoute: typeof AppFolhaRoute
  AppInicioRoute: typeof AppInicioRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPendentesRoute: typeof AppPendentesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPixRoute: typeof AppPixRoute
  AppSegurancaRoute: typeof AppSegurancaRoute
  AppSplitRoute: typeof AppSplitRoute
  AppTransferirRoute: typeof AppTransferirRoute
  AppComprovanteIdRoute: typeof AppComprovanteIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjudaRoute: AppAjudaRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCartoesRoute: AppCartoesRoute,
  AppConfigRoute: AppConfigRoute,
  AppContasRoute: AppContasRoute,
  AppConvitesRoute: AppConvitesRoute,
  AppDepositarRoute: AppDepositarRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppExtratoRoute: AppExtratoRoute,
  AppFolhaRoute: AppFolhaRoute,
  AppInicioRoute: AppInicioRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPendentesRoute: AppPendentesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPixRoute: AppPixRoute,
  AppSegurancaRoute: AppSegurancaRoute,
  AppSplitRoute: AppSplitRoute,
  AppTransferirRoute: AppTransferirRoute,
  AppComprovanteIdRoute: AppComprovanteIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BemVindoRoute: BemVindoRoute,
  CriarContaRoute: CriarContaRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
