/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppContasRouteImport } from './routes/_app.contas'
import { Route as AppDepositarRouteImport } from './routes/_app.depositar'
import { Route as AppExtratoRouteImport } from './routes/_app.extrato'
import { Route as AppInicioRouteImport } from './routes/_app.inicio'
import { Route as AppLojaRouteImport } from './routes/_app.loja'
import { Route as AppTransferirRouteImport } from './routes/_app.transferir'
import { Route as AppViagensRouteImport } from './routes/_app.viagens'
import { Route as AppComprovanteIdRouteImport } from './routes/_app.comprovante.$id'
import { Route as AppLojaIdRouteImport } from './routes/_app.loja.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositarRoute = AppDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppLojaRoute = AppLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferirRoute = AppTransferirRouteImport.update({
  id: '/transferir',
  path: '/transferir',
  getParentRoute: () => AppRoute,
} as any)
const AppViagensRoute = AppViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AppRoute,
} as any)
const AppComprovanteIdRoute = AppComprovanteIdRouteImport.update({
  id: '/comprovante/$id',
  path: '/comprovante/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLojaIdRoute = AppLojaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLojaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/contas': typeof AppContasRoute
  '/depositar': typeof AppDepositarRoute
  '/extrato': typeof AppExtratoRoute
  '/inicio': typeof AppInicioRoute
  '/loja': typeof AppLojaRouteWithChildren
  '/transferir': typeof AppTransferirRoute
  '/viagens': typeof AppViagensRoute
  '/comprovante/$id': typeof AppComprovanteIdRoute
  '/loja/$id': typeof AppLojaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/contas': typeof AppContasRoute
  '/depositar': typeof AppDepositarRoute
  '/extrato': typeof AppExtratoRoute
  '/inicio': typeof AppInicioRoute
  '/loja': typeof AppLojaRouteWithChildren
  '/transferir': typeof AppTransferirRoute
  '/viagens': typeof AppViagensRoute
  '/comprovante/$id': typeof AppComprovanteIdRoute
  '/loja/$id': typeof AppLojaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/bem-vindo': typeof BemVindoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/_app/contas': typeof AppContasRoute
  '/_app/depositar': typeof AppDepositarRoute
  '/_app/extrato': typeof AppExtratoRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/loja': typeof AppLojaRouteWithChildren
  '/_app/transferir': typeof AppTransferirRoute
  '/_app/viagens': typeof AppViagensRoute
  '/_app/comprovante/$id': typeof AppComprovanteIdRoute
  '/_app/loja/$id': typeof AppLojaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bem-vindo'
    | '/criar-conta'
    | '/login'
    | '/contas'
    | '/depositar'
    | '/extrato'
    | '/inicio'
    | '/loja'
    | '/transferir'
    | '/viagens'
    | '/comprovante/$id'
    | '/loja/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bem-vindo'
    | '/criar-conta'
    | '/login'
    | '/contas'
    | '/depositar'
    | '/extrato'
    | '/inicio'
    | '/loja'
    | '/transferir'
    | '/viagens'
    | '/comprovante/$id'
    | '/loja/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/bem-vindo'
    | '/criar-conta'
    | '/login'
    | '/_app/contas'
    | '/_app/depositar'
    | '/_app/extrato'
    | '/_app/inicio'
    | '/_app/loja'
    | '/_app/transferir'
    | '/_app/viagens'
    | '/_app/comprovante/$id'
    | '/_app/loja/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BemVindoRoute: typeof BemVindoRoute
  CriarContaRoute: typeof CriarContaRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contas': {
      id: '/_app/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depositar': {
      id: '/_app/depositar'
      path: '/depositar'
      fullPath: '/depositar'
      preLoaderRoute: typeof AppDepositarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extrato': {
      id: '/_app/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loja': {
      id: '/_app/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AppLojaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transferir': {
      id: '/_app/transferir'
      path: '/transferir'
      fullPath: '/transferir'
      preLoaderRoute: typeof AppTransferirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viagens': {
      id: '/_app/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof AppViagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comprovante/$id': {
      id: '/_app/comprovante/$id'
      path: '/comprovante/$id'
      fullPath: '/comprovante/$id'
      preLoaderRoute: typeof AppComprovanteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loja/$id': {
      id: '/_app/loja/$id'
      path: '/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof AppLojaIdRouteImport
      parentRoute: typeof AppLojaRoute
    }
  }
}

interface AppLojaRouteChildren {
  AppLojaIdRoute: typeof AppLojaIdRoute
}

const AppLojaRouteChildren: AppLojaRouteChildren = {
  AppLojaIdRoute: AppLojaIdRoute,
}

const AppLojaRouteWithChildren =
  AppLojaRoute._addFileChildren(AppLojaRouteChildren)

interface AppRouteChildren {
  AppContasRoute: typeof AppContasRoute
  AppDepositarRoute: typeof AppDepositarRoute
  AppExtratoRoute: typeof AppExtratoRoute
  AppInicioRoute: typeof AppInicioRoute
  AppLojaRoute: typeof AppLojaRouteWithChildren
  AppTransferirRoute: typeof AppTransferirRoute
  AppViagensRoute: typeof AppViagensRoute
  AppComprovanteIdRoute: typeof AppComprovanteIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContasRoute: AppContasRoute,
  AppDepositarRoute: AppDepositarRoute,
  AppExtratoRoute: AppExtratoRoute,
  AppInicioRoute: AppInicioRoute,
  AppLojaRoute: AppLojaRouteWithChildren,
  AppTransferirRoute: AppTransferirRoute,
  AppViagensRoute: AppViagensRoute,
  AppComprovanteIdRoute: AppComprovanteIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BemVindoRoute: BemVindoRoute,
  CriarContaRoute: CriarContaRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
